### PR TITLE
Develope

### PR DESCRIPTION
**Pull request by iggy-ziggy**
Added Foundation framework. Had to reorganize a little bit. Our file for adding JavaScript is now called app.js (just a naming scheme that came with downloading the framework, no real change), our CSS file is now app.css (same deal), and we have a JS vendor folder that contains all the JavaScript for Foundation. We don't need to touch that at all, it just makes all the dropdowns and widgets and such work.

### CODE REVIEW

**Review by larsly — COMMENTED** [review]
nice it looks good! thanks for being so descriptive!

**Review by iphaminh — APPROVED** [review]
looking good

**Review by larsly — COMMENTED** [review]
nice job

**Review by larsly — APPROVED** [review]
nice job :)

**Pull request merged**
